import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../../components/Navbar'
import Head from "next/head";
import Script from "next/script";
import 'bootstrap/dist/css/bootstrap.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
    <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
    
      <body className={inter.className}>
        <Navbar />
        {children}

        <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossOrigin="anonymous"
      />

      <Script src="https://kit.fontawesome.com/0351d91eea.js" crossorigin="anonymous"></Script>
      </body>
     
    </html>
    </>
  )
}
